name: Gaze
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    from: 2.5.0

targets:
  Gaze:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: Gaze
        excludes:
          - Tests
    info:
      path: Gaze/Info.plist
      properties:
        LSUIElement: true
        CFBundleName: Gaze
        CFBundleDisplayName: Gaze
        CFBundleIdentifier: com.gaze.Gaze
        CFBundleVersion: "2"
        CFBundleShortVersionString: "1.0.1"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        SUFeedURL: "https://AtharvaBari.github.io/Gaze/appcast.xml"
        SUEnableAutomaticChecks: true
        SUPublicEDKey: "rIBVwBzLoQwef7fvTQZEsWXSvFDUK46zI6qji9GG95g="
    dependencies:
      - package: Sparkle
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
